name: Container 1
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:latest
        with:
          entrypoint: "/bin/echo"
          args: "Hello World"
      - name: Log node version
        uses: docker://node:latest
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: Run a script
        uses: docker://node:latest
        with:
          entrypoint: ./script.sh
          args: "Some string"
      - name: send a slack message
        uses: docker://technosophos/slack-notify
        env: 
          SLACK_WEBHOOK: 'https://hooks.slack.com/services/TL05UC19&/BSFA4J6AU/AtqR75ARIGB0GCwYSZmMZzEE'
          SLACK_MESSAGE: "Hello slack"
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
      