name: Container 1
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker
        uses: docker://alialaa17/node-api
        with:
          entrypoint: "/bin/echo"
          args: "Hello World"
      - name: Log node version
        uses: docker://alialaa17/node-api
        with:
          entrypoint: /usr/local/bin/node
          args: -v
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release